trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ConferenceHub/**
    exclude:
      - Learning Path/**

pool:
  name: 'Minecraft server 2'
 # vmImage: 'ubuntu-latest'

variables:
  azureServiceConnectionName: 'Azure Service Connection'
  webAppName: 'app-conferencehub'
  appType: 'webAppLinux'
  appName: 'app-conferencehub'

pr: none

stages:
  - stage: Deploy_App_stage
    displayName: 'Deploy Application'
    jobs:
      - job: Deploy_App_job
        steps:
          - template: build-deploy-webapp-template.yaml
            parameters:
              webAppName: $(appName)
              appServiceName: $(webAppName)
              appType: $(appType)
              azureServiceConnectionName: $(azureServiceConnectionName)
