trigger: none
#  branches:
#    include:
#      - main
#  paths:
#    include:
#      - .ado/*
#      - .azure/*

pool:
  name: 'Minecraft server 2'
 # vmImage: 'ubuntu-latest'

variables:
  azureServiceConnectionName: 'Azure Service Connection'
  location: 'swedencentral'
  resourceGroupName: 'rg-conferencehub'
  appServicePlanName: 'plan-conferencehub'
  webAppName: 'app-conferencehub'
  appServicePlanSku: 'S1'
  appRuntime: 'DOTNETCORE|10.0'
  appCommandLine: '/home/site/wwwroot/ConferenceHub'
  appType: 'webAppLinux'

pr: none

stages:
  - stage: Deploy_Infrastructure_stage
    displayName: 'Deploy Infrastructure'

    jobs:
      - job: Deploy_Infrastructure_jobs

        steps:
          - task: AzureCLI@2
            displayName: Create or update the resource group
            inputs:
              azureSubscription: '$(azureServiceConnectionName)'
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az group create --location $(location) --name $(resourceGroupName)

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploy all infrastructure'
            inputs:
              connectedServiceName: $(azureServiceConnectionName)
              location: $(location)
              resourceGroupName: $(resourceGroupName)
              csmFile: ConferenceHub/devops/main.bicep
              overrideParameters: 
                -appServicePlanName $(appServicePlanName)
                -webAppName $(webAppName)
                -appServicePlanSku $(appServicePlanSku)
                -appRuntime $(appRuntime)
                -appCommandLine $(appCommandLine)
              deploymentOutputs: infrastructureAsCodeOutputs

  - stage: Deploy_App_stage
    displayName: 'Deploy Application'
    dependsOn: Deploy_Infrastructure_stage
    jobs:
      - job: Deploy_App_job
        steps:
          - template: build-deploy-webapp-template.yaml
            parameters:
              webAppName: 'ConferenceHub'
              appServiceName: $(webAppName)
              appType: $(appType)
              azureServiceConnectionName: $(azureServiceConnectionName)
