trigger: none
#  branches:
#    include:
#      - main
#  paths:
#    include:
#      - .ado/*
#      - .azure/*

pool:
  name: 'Minecraft server 2'
 # vmImage: 'ubuntu-latest'

variables:
  azureServiceConnectionName: 'Azure Service Connection'
  location: 'swedencentral'
  resourceGroupName: 'rg-conferencehub'
  appServicePlanName: 'plan-conferencehub'
  webAppName: 'app-conferencehub'
  appServicePlanSku: 'S1'
  appRuntime: 'DOTNETCORE|10.0'
  appType: 'webApp'

pr: none

stages:
  - stage: Deploy_Infrastructure_stage
    displayName: 'Deploy Infrastructure'

    jobs:
      - job: Deploy_Infrastructure_jobs

        steps:
          - task: AzureCLI@2
            displayName: Create or update the resource group
            inputs:
              azureSubscription: '$(azureServiceConnectionName)'
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az group create --location $(location) --name $(resourceGroupName)

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploy all infrastructure'
            inputs:
              connectedServiceName: $(azureServiceConnectionName)
              location: $(location)
              resourceGroupName: $(resourceGroupName)
              csmFile: .azure/bicep/infrastructure.bicep
              overrideParameters: 
                -appName $(appName)
                -env $(environment)
              deploymentOutputs: infrastructureAsCodeOutputs

  - stage: 
    displayName: 'Build/Depoy WebApplication1 webapp'
    dependsOn: 'Deploy_Infrastructure_stage'

    variables:
      webAppName: WebApplication1
      applicationName: az204

    jobs:
      - job:
        steps:
          - template: build-deploy-webapp-template.yaml
            parameters:
              webAppName: $(webAppName)
              appServiceName: $(appServicePlanName)
              appType: webApp
              azureServiceConnectionName: $(azureServiceConnectionName)

