parameters:
  - name: webAppName
    type: string

  - name: appServiceName
    type: string
  
  - name: appType
    type: string
  
  - name: azureServiceConnectionName
    type: string

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 10.0 SDK'
    inputs:
      packageType: 'sdk'
      version: '10.x'

  - script: |
      rm -rf "$(Build.SourcesDirectory)/.pipeline/publish"
      mkdir -p "$(Build.SourcesDirectory)/.pipeline/publish"
    displayName: 'Prepare publish directory'

  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
      projects: '$(System.DefaultWorkingDirectory)/ConferenceHub/ConferenceHub.csproj'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: 'Build and publish'
    inputs:
      command: 'publish'
      projects: '$(System.DefaultWorkingDirectory)/ConferenceHub/ConferenceHub.csproj'
      publishWebProjects: false
      arguments: '-o $(Build.SourcesDirectory)/.pipeline/publish --configuration Release -r linux-x64 --self-contained true'

  - script: |
      echo "Publish output:"
      ls -la "$(Build.SourcesDirectory)/.pipeline/publish"
    displayName: 'Inspect publish output'

  - task: ArchiveFiles@2
    displayName: 'Archive publish output'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/.pipeline/publish'
      includeRootFolder: false
      archiveType: zip
      archiveFile: '$(Build.ArtifactStagingDirectory)/${{ parameters.webAppName }}.zip'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/${{ parameters.webAppName }}.zip'
      artifact: ${{ parameters.appServiceName }}
      publishLocation: 'pipeline'

  - script: |
          echo "webAppName: ${{ parameters.webAppName }}"
          echo "appServiceName: ${{ parameters.appServiceName }}"
          echo "appType: ${{ parameters.appType }}"
          echo "azureServiceConnectionName: ${{ parameters.azureServiceConnectionName }}"
          echo "targetPath: $(Build.SourcesDirectory)/.pipeline/publish"
          echo "artifact: ${{ parameters.appServiceName }}"
          echo "package: $(Build.ArtifactStagingDirectory)/${{ parameters.webAppName }}.zip"

    displayName: 'Print variables using Bash from build-deploy-webapp-template.yaml'

  - task: AzureWebApp@1
    displayName: 'Deploy Azure Web App'
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnectionName }}
      appType: ${{ parameters.appType }}
      appName: ${{ parameters.appServiceName }}
      package: '$(Build.ArtifactStagingDirectory)/${{ parameters.webAppName }}.zip'
