trigger: none
#  branches:
#    include:
#      - main
#  paths:
#    include:
#      - .ado/*
#      - .azure/*

pool:
  name: 'Minecraft server 2'
 # vmImage: 'ubuntu-latest'

variables:
  azureServiceConnectionName: 'Azure Service Connection'
  location: 'swedencentral'
  resourceGroupName: 'rg-conferencehub'
  appServicePlanName: 'plan-conferencehub'
  appName: 'app-conferencehub'

  appServicePlanSku: 'S1'
  appRuntime: 'DOTNETCORE|10.0'
  appType: 'webApp'
  System.Debug: true
  environment: demo

pr: none

stages:
  - stage: 
    displayName: 'Build/Depoy WebApplication1 webapp'
    dependsOn: 'Deploy_Infrastructure_stage'

    jobs:
      - job:
        steps:
          - template: build-deploy-webapp-template.yaml
            parameters:
              webAppName: $(appName)
              appServiceName: $(appServicePlanName)
              appType: webApp
              azureServiceConnectionName: $(azureServiceConnectionName)